### ISSUE TITLE
Review cw-storage library

### ISSUE THREAD

**Issue by ethanfrey** [confio/crev-proofs#1]
Use `crev` tool and publish a review. This should be someone besides me (the author).

There are instructions on how to use crev here: https://github.com/cosmwasm/docs/pull/23
(follow verify and reviews here: https://github.com/cosmwasm/docs/tree/reviews/docs/tooling ... and maybe give a PR review on that as well)

Also, please add a PR review to add your name to the CosmWasm developers list on the bottom of `reviews.md` in that PR

**Comment by clevinson** [comment]
@ethanfrey Assume you're referring to this library https://github.com/confio/cw-storage ?

I just setup crev (https://github.com/clevinson/crev-proofs) and can review this library tomorrow.

**Comment by ethanfrey** [comment]
That is correct.
I will add you to my crev web of trust

**Comment by ethanfrey** [comment]
@clevinson Done. https://github.com/ethanfrey/crev-proofs/commit/c61ea4aaef630530de5a33d87638d48d5632c415

**Comment by clevinson** [comment]
@ethanfrey i'm on this. Can you assign to me?

**Comment by clevinson** [comment]
This is now done https://github.com/clevinson/crev-proofs/commit/a11e818f312c036f912a0d15f12eb92060bc43ef

I've also added myself to the docs page (see PR [here](https://github.com/cosmwasm/docs/pull/25/files))

**Comment by ethanfrey** [comment]
Thank you
